export const LOCALES = [
  ['en','English'],['es','Español'],['de','Deutsch'],['ja','日本語'],['fr','Français'],['pt','Português'],['ru','Русский'],['it','Italiano'],['zh','中文'],['ar','العربية']
];

const DICT = {
  en:{home:'Home',recent:'Recent',library:'Library',templates:'Templates',pdf:'PDF Studio',documents:'Document Editor',tools:'All Tools',settings:'Settings',about:'About',open:'Open',openFile:'Open File',newDocument:'New Document',goodMorning:'Good morning',privacy:'Local processing',ready:'Ready',theme:'Theme',language:'Language',appearance:'Appearance',pro:'Pro',free:'Free',save:'Save',saveAs:'Save As',exportPdf:'Export PDF',find:'Find',replace:'Replace',undo:'Undo',redo:'Redo',insert:'Insert',layout:'Layout',review:'Review',view:'View',protect:'Protect',comment:'Comment',fillSign:'Fill & Sign',organize:'Organize Pages',ocrSearch:'OCR & Search',scanFolders:'Scan Common Folders'},
  es:{home:'Inicio',recent:'Recientes',library:'Biblioteca',templates:'Plantillas',pdf:'Estudio PDF',documents:'Editor de documentos',tools:'Todas las herramientas',settings:'Configuración',about:'Acerca de',open:'Abrir',openFile:'Abrir archivo',newDocument:'Nuevo documento',goodMorning:'Buenos días',privacy:'Procesamiento local',ready:'Listo',theme:'Tema',language:'Idioma',appearance:'Apariencia',pro:'Pro',free:'Gratis',save:'Guardar',saveAs:'Guardar como',exportPdf:'Exportar PDF',find:'Buscar',replace:'Reemplazar',undo:'Deshacer',redo:'Rehacer',insert:'Insertar',layout:'Diseño',review:'Revisar',view:'Vista',protect:'Proteger',comment:'Comentario',fillSign:'Rellenar y firmar',organize:'Organizar páginas',ocrSearch:'OCR y búsqueda',scanFolders:'Escanear carpetas comunes'},
  de:{home:'Start',recent:'Zuletzt',library:'Bibliothek',templates:'Vorlagen',pdf:'PDF Studio',documents:'Dokumenteditor',tools:'Alle Werkzeuge',settings:'Einstellungen',about:'Info',open:'Öffnen',openFile:'Datei öffnen',newDocument:'Neues Dokument',goodMorning:'Guten Morgen',privacy:'Lokale Verarbeitung',ready:'Bereit',theme:'Design',language:'Sprache',appearance:'Darstellung',pro:'Pro',free:'Kostenlos',save:'Speichern',saveAs:'Speichern unter',exportPdf:'PDF exportieren',find:'Suchen',replace:'Ersetzen',undo:'Rückgängig',redo:'Wiederholen',insert:'Einfügen',layout:'Layout',review:'Überprüfen',view:'Ansicht',protect:'Schützen',comment:'Kommentar',fillSign:'Ausfüllen & signieren',organize:'Seiten organisieren',ocrSearch:'OCR & Suche',scanFolders:'Standardordner scannen'},
  ja:{home:'ホーム',recent:'最近',library:'ライブラリ',templates:'テンプレート',pdf:'PDF スタジオ',documents:'文書エディター',tools:'すべてのツール',settings:'設定',about:'情報',open:'開く',openFile:'ファイルを開く',newDocument:'新規文書',goodMorning:'おはようございます',privacy:'ローカル処理',ready:'準備完了',theme:'テーマ',language:'言語',appearance:'外観',pro:'Pro',free:'無料',save:'保存',saveAs:'名前を付けて保存',exportPdf:'PDFを書き出す',find:'検索',replace:'置換',undo:'元に戻す',redo:'やり直す',insert:'挿入',layout:'レイアウト',review:'校閲',view:'表示',protect:'保護',comment:'コメント',fillSign:'入力と署名',organize:'ページを整理',ocrSearch:'OCRと検索',scanFolders:'標準フォルダーをスキャン'},
  fr:{home:'Accueil',recent:'Récents',library:'Bibliothèque',templates:'Modèles',pdf:'Studio PDF',documents:'Éditeur de documents',tools:'Tous les outils',settings:'Paramètres',about:'À propos',open:'Ouvrir',openFile:'Ouvrir un fichier',newDocument:'Nouveau document',goodMorning:'Bonjour',privacy:'Traitement local',ready:'Prêt',theme:'Thème',language:'Langue',appearance:'Apparence',pro:'Pro',free:'Gratuit',save:'Enregistrer',saveAs:'Enregistrer sous',exportPdf:'Exporter en PDF',find:'Rechercher',replace:'Remplacer',undo:'Annuler',redo:'Rétablir',insert:'Insertion',layout:'Mise en page',review:'Révision',view:'Affichage',protect:'Protéger',comment:'Commentaire',fillSign:'Remplir et signer',organize:'Organiser les pages',ocrSearch:'OCR et recherche',scanFolders:'Analyser les dossiers courants'},
  pt:{home:'Início',recent:'Recentes',library:'Biblioteca',templates:'Modelos',pdf:'Estúdio PDF',documents:'Editor de documentos',tools:'Todas as ferramentas',settings:'Definições',about:'Sobre',open:'Abrir',openFile:'Abrir ficheiro',newDocument:'Novo documento',goodMorning:'Bom dia',privacy:'Processamento local',ready:'Pronto',theme:'Tema',language:'Idioma',appearance:'Aparência',pro:'Pro',free:'Grátis',save:'Guardar',saveAs:'Guardar como',exportPdf:'Exportar PDF',find:'Localizar',replace:'Substituir',undo:'Desfazer',redo:'Refazer',insert:'Inserir',layout:'Layout',review:'Revisão',view:'Ver',protect:'Proteger',comment:'Comentário',fillSign:'Preencher e assinar',organize:'Organizar páginas',ocrSearch:'OCR e pesquisa',scanFolders:'Analisar pastas comuns'},
  ru:{home:'Главная',recent:'Недавние',library:'Библиотека',templates:'Шаблоны',pdf:'PDF Студия',documents:'Редактор документов',tools:'Все инструменты',settings:'Настройки',about:'О программе',open:'Открыть',openFile:'Открыть файл',newDocument:'Новый документ',goodMorning:'Доброе утро',privacy:'Локальная обработка',ready:'Готово',theme:'Тема',language:'Язык',appearance:'Внешний вид',pro:'Pro',free:'Бесплатно',save:'Сохранить',saveAs:'Сохранить как',exportPdf:'Экспорт PDF',find:'Найти',replace:'Заменить',undo:'Отменить',redo:'Повторить',insert:'Вставка',layout:'Макет',review:'Рецензирование',view:'Вид',protect:'Защитить',comment:'Комментарий',fillSign:'Заполнить и подписать',organize:'Организовать страницы',ocrSearch:'OCR и поиск',scanFolders:'Сканировать стандартные папки'},
  it:{home:'Home',recent:'Recenti',library:'Libreria',templates:'Modelli',pdf:'Studio PDF',documents:'Editor documenti',tools:'Tutti gli strumenti',settings:'Impostazioni',about:'Informazioni',open:'Apri',openFile:'Apri file',newDocument:'Nuovo documento',goodMorning:'Buongiorno',privacy:'Elaborazione locale',ready:'Pronto',theme:'Tema',language:'Lingua',appearance:'Aspetto',pro:'Pro',free:'Gratis',save:'Salva',saveAs:'Salva con nome',exportPdf:'Esporta PDF',find:'Trova',replace:'Sostituisci',undo:'Annulla',redo:'Ripristina',insert:'Inserisci',layout:'Layout',review:'Revisione',view:'Visualizza',protect:'Proteggi',comment:'Commento',fillSign:'Compila e firma',organize:'Organizza pagine',ocrSearch:'OCR e ricerca',scanFolders:'Scansiona cartelle comuni'},
  zh:{home:'主页',recent:'最近',library:'资料库',templates:'模板',pdf:'PDF 工作室',documents:'文档编辑器',tools:'全部工具',settings:'设置',about:'关于',open:'打开',openFile:'打开文件',newDocument:'新建文档',goodMorning:'早上好',privacy:'本地处理',ready:'就绪',theme:'主题',language:'语言',appearance:'外观',pro:'专业版',free:'免费版',save:'保存',saveAs:'另存为',exportPdf:'导出 PDF',find:'查找',replace:'替换',undo:'撤销',redo:'重做',insert:'插入',layout:'布局',review:'审阅',view:'视图',protect:'保护',comment:'批注',fillSign:'填写与签名',organize:'整理页面',ocrSearch:'OCR 与搜索',scanFolders:'扫描常用文件夹'},
  ar:{home:'الرئيسية',recent:'الأخيرة',library:'المكتبة',templates:'القوالب',pdf:'استوديو PDF',documents:'محرر المستندات',tools:'كل الأدوات',settings:'الإعدادات',about:'حول',open:'فتح',openFile:'فتح ملف',newDocument:'مستند جديد',goodMorning:'صباح الخير',privacy:'معالجة محلية',ready:'جاهز',theme:'السمة',language:'اللغة',appearance:'المظهر',pro:'احترافي',free:'مجاني',save:'حفظ',saveAs:'حفظ باسم',exportPdf:'تصدير PDF',find:'بحث',replace:'استبدال',undo:'تراجع',redo:'إعادة',insert:'إدراج',layout:'تخطيط',review:'مراجعة',view:'عرض',protect:'حماية',comment:'تعليق',fillSign:'تعبئة وتوقيع',organize:'تنظيم الصفحات',ocrSearch:'OCR وبحث',scanFolders:'فحص المجلدات الشائعة'}
};

export function localeFromSystem(){
  const raw=(navigator.language||'en').toLowerCase();
  const exact=LOCALES.find(([id])=>raw===id||raw.startsWith(id+'-'));
  return exact?.[0]||'en';
}
export function makeT(locale='en'){
  const d=DICT[locale]||DICT.en;
  return (key,fallback)=>d[key]||DICT.en[key]||fallback||key;
}
export function isRtl(locale){return locale==='ar';}
